"""add report new fields

Revision ID: 7f9c732ee2d3
Revises: 
Create Date: 2026-07-07 15:45:48.815413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9c732ee2d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('format', sa.String(length=20), nullable=True))
    op.add_column('reports', sa.Column('data_range', sa.String(length=50), nullable=True))
    op.add_column('reports', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('download_count', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'updated_at')
    op.drop_column('reports', 'download_count')
    op.drop_column('reports', 'file_size')
    op.drop_column('reports', 'data_range')
    op.drop_column('reports', 'format')
    # ### end Alembic commands ###
